apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-appsource-controller
  labels:
    app.kubernetes.io/name: argocd-appsource-controller
    app.kubernetes.io/part-of: argocd-appsource
    app.kubernetes.io/component: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-appsource-controller
subjects:
- kind: ServiceAccount
  name: argocd-appsource-controller
